### ISSUE TITLE
About state comparison for the List Validator. 

### ISSUE THREAD

**Issue by mcalancea** [runtimeverification/casper-cbc-proofs#119]
Monday (5.10.20) we touched on a question regarding the comparison operator for List Validator states. I'll try to pose the question in a clearer way here.

Let's say we have a node `A`, which experienced the following trace:
`initial_state -> update 0 -> receive from B` which results in the state `s_mid`.
and then continued to experience: 
`initial_state -> update 0 -> receive from B -> receive from C -> update 1`, resulting in the state `s`. 

The question is: should the pair `s_mid` and `s` count as equivocation evidence?

`s` is clearly a possible future state of `s_mid`, so it is tempting to answer NO. However, we should note that in our case `A` has not sent the message `(A, s_mid)` and it never will. So if there by chance exists a validator Z, such that `project Z A = s_mid`, it is impossible for `Z` to receive messages until `project Z A = s` (because there's no message sent by `A` which meets the valid receive condition). So we will be unable to make everyone agree on `A`'s state but we will also be unable to prove that `A` is equivocating, thus contradicting the common futures result. 

Another thing is that if `s_mid` appears as an observation pertaining to validator `A`, it seems we can prove that there exists an equivocating message according to the VLSM definition. 

For there reasons, we think that `s_mid` and `s` _should_ count as equivocation evidence, although `s` is a possible future state of `s_mid`.

**Comment by mcalancea** [comment]
On Wednesday we decided that we should extend the concept of observations for the list validator to include the actual state of a given validator (which we can observe and use in the composition constraint). We call these observations "state-based "and the original observations "message-based" (and also distinguish between received and sent). 

One question which arises: consider `s_mid` and `s` from the above example. If `s_mid` is a state-based observation and `s` a message-based one, they should, intuitively , constitute equivocation evidence. However, this evidence will not be persistent, as it is possible that the validator eventually reaches state `s`. So we have equivocation that might manifest itself presently, but "repair" itself in the future.

The common futures result doesn't _seem _to be affected by this, but in general this type of "transient" equivocation may be a delicate problem?

**Comment by traiansf** [comment]
`subject_vlsm_component` attached to `event` as  "subject of observation"
