### ISSUE TITLE
Refining the relationship between traces, transition functions and composition constraints

### ISSUE THREAD

**Issue by rooibosriot** [runtimeverification/casper-cbc-proofs#24]
Towards clarifying the relationship between component VLSMs, composed VLSMs, and VLSM projections: 

- [ ] Lemma: traces of the same type are uniquely identified by their initial state and transition function 

In terms of transition functions: VLSM composition can be seen as first _expanding_ the message domain (VLSMs under composition can freely receive messages that might not have been available to it individually), i.e. the inputs to the transition function, and then _restricting_ the transition function under this new domain. 

- [ ] Lemma: all traces that are available under a composition constraint are available under free composition (trivial) 

- [ ] Lemma: all traces that are available to a projection are available to the composition under the composition constraint (but not necessarily vice versa) 

- [ ] Clarify the relationship between projection friendliness and composition constraints.

**Comment by traiansf** [comment]
These are either done or there exist duplicate issues with them,
